import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>مرحبا بكم في نظام المعلومات المدرسية</h3>
        <h4 className={styles.span}>(SIS)</h4>
        <p className={styles.description}>
          الخاص ب{" "}
          <code className={styles.code}>مدرسة فاطمة الزهراء الثانوية بنات</code>
        </p>
      </main>
    </div>
  );
}
